services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1029
      - POSTGRES_DB=postgres
      - DB_HOST=localhost

  db:
    image: postgres:13
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: 1029
      POSTGRES_DB: docker_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
